# Generated by Django 3.2 on 2022-01-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fct_deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis', models.CharField(blank=True, max_length=1000, null=True)),
                ('band1', models.CharField(blank=True, max_length=1000, null=True)),
                ('band2', models.CharField(blank=True, max_length=1000, null=True)),
                ('band3', models.CharField(blank=True, max_length=1000, null=True)),
                ('fct1', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('fct2', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('fct3', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('eff_rate1', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('eff_rate2', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('eff_rate3', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('rev1', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('rev2', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('rev3', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('total_rev', models.IntegerField(max_length=1000)),
                ('total_fct', models.IntegerField(max_length=1000)),
                ('prev_yr_fct', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('curr_fct', models.IntegerField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
