# Generated by Django 3.2 on 2022-01-31 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('channel', models.CharField(blank=True, choices=[('INN', 'INN'), ('NX', 'NX'), ('IN UP', 'IN UP'), ('MP', 'MP'), ('RAJ', 'RAJ'), ('PUN', 'PUN'), ('HAR', 'HAR'), ('GUJ', 'GUJ'), ('NE NEWS', 'NE NEWS')], max_length=1000, null=True)),
                ('dispersion', models.CharField(blank=True, max_length=1000, null=True)),
                ('bands', models.CharField(blank=True, max_length=1000, null=True)),
                ('br', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
