# Generated by Django 3.2 on 2022-02-04 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0002_alter_base_rate_table_unique_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_rate_table',
            name='ref_b_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deal_fct_nonfct.band'),
        ),
        migrations.AddField(
            model_name='base_rate_table',
            name='ref_c_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deal_fct_nonfct.channel'),
        ),
    ]
