# Generated by Django 3.2 on 2022-02-01 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0003_alter_base_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
