# Generated by Django 3.2 on 2022-02-01 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0004_alter_base_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
