# Generated by Django 3.2 on 2022-02-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0006_remove_fct_deal_total_fct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fct_deal',
            name='eff_rate3',
            field=models.IntegerField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='fct3',
            field=models.IntegerField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='rev3',
            field=models.IntegerField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
