# Generated by Django 3.2.11 on 2022-01-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencydetail',
            name='a_id',
            field=models.CharField(default='default', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
