# Generated by Django 3.2.11 on 2022-01-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_agencycontact_agency_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencycontact',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
