# Generated by Django 3.2.11 on 2022-01-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_agencycontact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencycontact',
            name='ac_id',
            field=models.CharField(default='default', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
