# Generated by Django 3.2.11 on 2022-02-23 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='ref_cname',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='cust_name', to='customer.customername'),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='ref_creg_no',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='cust_ref', to='customer.customername'),
        ),
    ]
