# Generated by Django 3.2.11 on 2022-02-09 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFCT_Base_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfct_unique_key', models.CharField(blank=True, max_length=100, null=True)),
                ('nfct_baserate', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NFCT_Channels',
            fields=[
                ('nfct_channels', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NFCT_Elements',
            fields=[
                ('nfct_elements', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NFCTDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durations', models.CharField(blank=True, choices=[('days', 'Days'), ('months', 'Months')], max_length=6, null=True)),
                ('duration_in', models.IntegerField(blank=True, null=True)),
                ('effective_rate', models.IntegerField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('total_seconds', models.IntegerField(blank=True, null=True)),
                ('base_rate', models.IntegerField(blank=True, null=True)),
                ('nfct_total', models.IntegerField(blank=True, null=True)),
                ('ref_nfct_channels', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nfct.nfct_channels')),
                ('ref_nfct_elements', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nfct.nfct_elements')),
            ],
        ),
    ]
