# Generated by Django 3.2.11 on 2022-03-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal_nfct',
            name='main_dealid_nfct_ref',
            field=models.CharField(blank=True, default='default', max_length=100, null=True),
        ),
    ]
