# Generated by Django 3.2.11 on 2022-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCT_Elements',
            fields=[
                ('nfct_elements', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
