# Generated by Django 3.2.11 on 2022-02-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctdeal',
            name='ref_nfct_channels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='nfct.nfct_channels'),
        ),
    ]
