# Generated by Django 3.2.6 on 2022-02-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal_nfct',
            name='channel',
            field=models.CharField(choices=[('INN', 'INN'), ('NX', 'NX'), ('GUJ', 'GUJ'), ('HAR', 'HAR'), ('MP', 'MP'), ('NE NEWS', 'NE NEWS'), ('PUN', 'PUN'), ('RAJ', 'RAJ'), ('UP', 'UP')], max_length=255),
        ),
        migrations.AlterField(
            model_name='deal_nfct',
            name='element',
            field=models.CharField(choices=[('Aston', 'Aston'), ('L Band', 'L Band'), ('Logo Bug', 'Logo Bug'), ('Headline Sponsership Tag', 'Headline Sponsership Tag'), ('Ticker', 'Ticker'), ('Weather Branding', 'Weather Branding')], max_length=255),
        ),
        migrations.AlterField(
            model_name='nfct_base_rate',
            name='channel',
            field=models.CharField(choices=[('INN', 'INN'), ('NX', 'NX'), ('GUJ', 'GUJ'), ('HAR', 'HAR'), ('MP', 'MP'), ('NE NEWS', 'NE NEWS'), ('PUN', 'PUN'), ('RAJ', 'RAJ'), ('UP', 'UP')], max_length=255),
        ),
        migrations.AlterField(
            model_name='nfct_base_rate',
            name='element',
            field=models.CharField(choices=[('Aston', 'Aston'), ('L Band', 'L Band'), ('Logo Bug', 'Logo Bug'), ('Headline Sponsership Tag', 'Headline Sponsership Tag'), ('Ticker', 'Ticker'), ('Weather Branding', 'Weather Branding')], max_length=255),
        ),
    ]
