# Generated by Django 3.2.6 on 2022-02-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal_nfct',
            name='deal_id',
        ),
    ]
