# Generated by Django 3.2.11 on 2022-02-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfct', '0002_nfct_elements'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCT_Base_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfct_unique_key', models.CharField(blank=True, max_length=100, null=True)),
                ('nfct_baserate', models.IntegerField()),
            ],
        ),
    ]
