# Generated by Django 3.2.11 on 2022-02-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfct', '0002_alter_nfctdeal_ref_nfct_channels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfctdeal',
            old_name='ref_nfct_channels',
            new_name='ref_nfct_channels_id',
        ),
        migrations.RenameField(
            model_name='nfctdeal',
            old_name='ref_nfct_elements',
            new_name='ref_nfct_elements_id',
        ),
    ]
