# Generated by Django 3.2.11 on 2022-02-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfct', '0003_nfct_base_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfct_base_rate',
            name='nfct_baserate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
