# Generated by Django 3.2.11 on 2022-02-08 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfct', '0004_alter_nfct_base_rate_nfct_baserate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCTDeal',
            fields=[
                ('nfct_refrenece_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('durations', models.CharField(blank=True, choices=[('days', 'Days'), ('months', 'Months')], max_length=6, null=True)),
                ('effective_rate', models.IntegerField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('total_seconds', models.IntegerField(blank=True, null=True)),
                ('base_rate', models.IntegerField(blank=True, null=True)),
                ('nfct_total', models.IntegerField(blank=True, null=True)),
                ('ref_nfct_channels', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nfct.nfct_channels')),
                ('ref_nfct_elements', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nfct.nfct_elements')),
            ],
        ),
    ]
