# Generated by Django 3.2.11 on 2022-03-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfct', '0005_auto_20220303_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalnfct',
            name='grandtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
