# Generated by Django 3.2.11 on 2022-02-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfct', '0005_nfctdeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctdeal',
            name='duration_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
