# Generated by Django 3.2.11 on 2022-03-04 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nfct', '0006_finalnfct_grandtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal_nfct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
