# Generated by Django 3.2.11 on 2022-01-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('ref_customertype', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='customer.customertype')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('cc_fname', models.CharField(max_length=50)),
                ('cc_lname', models.CharField(max_length=50)),
                ('cc_designation', models.CharField(max_length=50)),
                ('cc_email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(default='default', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ref_cname', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='customer.customername')),
            ],
        ),
    ]
