# Generated by Django 3.2.11 on 2022-01-22 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('ctype_id', models.CharField(default='default', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('customer_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerName',
            fields=[
                ('cust_id', models.CharField(default='default', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('customertype', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='customer.customertype')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('cc_id', models.CharField(default='default', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('customername', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='customer.customername')),
            ],
        ),
    ]
