# Generated by Django 3.2.11 on 2022-02-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercontact',
            old_name='pri_designation',
            new_name='pri_desg',
        ),
        migrations.RenameField(
            model_name='customercontact',
            old_name='sec_designation',
            new_name='sec_desg',
        ),
    ]
