# Generated by Django 3.2.11 on 2022-01-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertype',
            name='ctype_id',
            field=models.CharField(default='default', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
