# Generated by Django 3.2.11 on 2022-01-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customertype_ctype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='cc_id',
            field=models.CharField(default='default', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
