# Generated by Django 3.2.11 on 2022-01-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customercontact_cc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
