# Generated by Django 4.0.1 on 2022-01-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=100)),
                ('items', models.CharField(blank=True, max_length=100, null=True)),
                ('price_unit', models.IntegerField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, max_length=100, null=True)),
                ('total', models.IntegerField(blank=True, max_length=100, null=True)),
                ('amt', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
