# Generated by Django 3.2.11 on 2022-01-24 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0005_alter_agencycontact_ac_id'),
        ('item', '0002_subitem_item'),
        ('customer', '0004_alter_customercontact_phone'),
        ('plan', '0002_alter_plan_p_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fct1', models.IntegerField(blank=True, null=True)),
                ('fct2', models.IntegerField(blank=True, null=True)),
                ('fct3', models.IntegerField(blank=True, null=True)),
                ('eff_rate1', models.IntegerField(blank=True, null=True)),
                ('eff_rate2', models.IntegerField(blank=True, null=True)),
                ('eff_rate3', models.IntegerField(blank=True, null=True)),
                ('base_rate1', models.IntegerField(blank=True, null=True)),
                ('base_rate2', models.IntegerField(blank=True, null=True)),
                ('base_rate3', models.IntegerField(blank=True, null=True)),
                ('slot1', models.IntegerField(blank=True, null=True)),
                ('slot2', models.IntegerField(blank=True, null=True)),
                ('slot3', models.IntegerField(blank=True, null=True)),
                ('actual_fct1', models.IntegerField(blank=True, null=True)),
                ('actual_fct2', models.IntegerField(blank=True, null=True)),
                ('actual_fct3', models.IntegerField(blank=True, null=True)),
                ('total_fct', models.IntegerField(blank=True, null=True)),
                ('total_members', models.IntegerField(blank=True, null=True)),
                ('agency_contact', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='agency.agencycontact')),
                ('agency_id', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='agency.agencydetail')),
                ('customer_contact', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='customer.customercontact')),
                ('customer_id', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='customer.customername')),
                ('item_id', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('plan_id', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
                ('subitem_id', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='item.subitem')),
            ],
        ),
    ]
