# Generated by Django 3.2.11 on 2022-01-24 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_deal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal_one',
            name='total_fct',
        ),
        migrations.RemoveField(
            model_name='deal_one',
            name='total_members',
        ),
    ]
