# Generated by Django 3.2.11 on 2022-02-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220209_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_pass1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_pass2',
            field=models.CharField(max_length=100),
        ),
    ]
