# Generated by Django 3.2.6 on 2022-03-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_fct_nfct_deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalfctnfctdeal',
            name='fct_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finalfctnfctdeal',
            name='nfct_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
