# Generated by Django 3.2.11 on 2022-03-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_fct_nfct_deal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalfctnfctdeal',
            name='id',
        ),
        migrations.AlterField(
            model_name='finalfctnfctdeal',
            name='deal_id',
            field=models.CharField(default='null', max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
