# Generated by Django 3.2.6 on 2022-02-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_fct_nfct_deal', '0002_auto_20220223_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalfctnfctdeal',
            name='fct_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalfctnfctdeal',
            name='nfct_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
