# Generated by Django 3.2.6 on 2022-03-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_fct_nfct_deal', '0002_auto_20220301_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalfctnfctdeal',
            name='fct_total',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='finalfctnfctdeal',
            name='nfct_total',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
