# Generated by Django 3.2 on 2022-03-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencydetail',
            name='agency_pin',
            field=models.IntegerField(),
        ),
    ]
