# Generated by Django 3.2.11 on 2022-03-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencycontact',
            name='pri_landline',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='agencycontact',
            name='sec_landline',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='pri_landline',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='sec_landline',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
