# Generated by Django 3.2.11 on 2022-03-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercontact',
            name='create_at',
        ),
        migrations.AddField(
            model_name='customername',
            name='agencies',
            field=models.ManyToManyField(to='agency_client.AgencyDetail'),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='pri_landline',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='sec_landline',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
