# Generated by Django 3.2.11 on 2022-03-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_client', '0002_auto_20220308_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customername',
            name='agencies',
        ),
    ]
