# Generated by Django 3.2 on 2022-03-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_client', '0002_alter_agencydetail_agency_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencydetail',
            name='customernames',
            field=models.ManyToManyField(to='agency_client.CustomerName'),
        ),
    ]
