# Generated by Django 3.2.6 on 2022-02-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_client', '0002_alter_customercontact_ref_cname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercontact',
            name='ref_cname',
        ),
    ]
