# Generated by Django 3.2.11 on 2022-03-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_client', '0003_remove_customername_agencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='customername',
            name='agencies',
            field=models.ManyToManyField(to='agency_client.AgencyDetail'),
        ),
    ]
