# Generated by Django 3.2 on 2022-03-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_client', '0003_agencydetail_customernames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencydetail',
            name='customernames',
        ),
    ]
