# Generated by Django 3.2.11 on 2022-03-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_client', '0004_customername_agencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customername',
            name='agencies',
        ),
    ]
