# Generated by Django 3.2.11 on 2022-02-05 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRateNFCT',
            fields=[
                ('unique_key', models.CharField(default='default', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('base_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChannelNFCT',
            fields=[
                ('channel', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElementNFCT',
            fields=[
                ('element', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealNFCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eff_rate', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('total_sec', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('baserate_nfct', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='deals.baseratenfct')),
                ('channel_nfct', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='deals.channelnfct')),
                ('element_nfct', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='deals.elementnfct')),
            ],
        ),
    ]
