# Generated by Django 3.2.11 on 2022-02-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealnfct',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealnfct',
            name='months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealnfct',
            name='seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
