# Generated by Django 3.2 on 2022-03-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFPBaseRate',
            fields=[
                ('br_unique_key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('baserate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AFPChannels',
            fields=[
                ('channels', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AFPDealFinalTotal',
            fields=[
                ('afp_final_total', models.IntegerField(primary_key=True, serialize=False)),
                ('afp_final_deal_id', models.CharField(default='default', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AFPProgramName',
            fields=[
                ('program_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AFPPromos',
            fields=[
                ('promos', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AFPSlots',
            fields=[
                ('slot', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AFPDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afp_deal_id', models.CharField(max_length=20, verbose_name='aFP Deal ID')),
                ('afp_eff_rate', models.CharField(max_length=200, verbose_name='effective Rate')),
                ('afp_base_rate', models.IntegerField(verbose_name='base Rate')),
                ('ref_channels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afp_deal.afpchannels', verbose_name='channel')),
                ('ref_program_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afp_deal.afpprogramname', verbose_name='program Name')),
                ('ref_promos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afp_deal.afppromos', verbose_name='promo')),
                ('ref_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afp_deal.afpslots', verbose_name='slot')),
            ],
        ),
    ]
