# Generated by Django 3.2.6 on 2022-03-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFPBaseRate',
            fields=[
                ('br_unique_key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('baserate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AFPChannels',
            fields=[
                ('channels', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AFPDealFinalTotal',
            fields=[
                ('afp_final_total', models.DecimalField(decimal_places=2, max_digits=12, primary_key=True, serialize=False)),
                ('afp_final_deal_id', models.CharField(default='default', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AFPProgramName',
            fields=[
                ('program_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AFPPromos',
            fields=[
                ('promos', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AFPSlots',
            fields=[
                ('slot', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinalAFPDeal',
            fields=[
                ('afpdeal_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('afp_ro_number', models.CharField(max_length=100)),
                ('afp_ro_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('afp_total_ref', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('afp_deal_created', models.DateTimeField(auto_now_add=True)),
                ('afp_agency_contact_ref', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='agency_client.agencycontact')),
                ('afp_agency_name_ref', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='agency_client.agencydetail')),
                ('afp_brand_name_ref', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='brand2', to='agency_client.customername')),
                ('afp_client_contact_ref', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='agency_client.customercontact')),
                ('afp_client_name_ref', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='client2', to='agency_client.customername')),
            ],
        ),
        migrations.CreateModel(
            name='AFPDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afp_deal_id', models.CharField(max_length=20)),
                ('ref_program_name', models.CharField(max_length=200, verbose_name='program Name')),
                ('ref_promos', models.CharField(max_length=200, verbose_name='promos')),
                ('afp_eff_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='effective Rate')),
                ('afp_base_rate', models.IntegerField(verbose_name='base Rate')),
                ('afp_created', models.DateTimeField(auto_now_add=True)),
                ('ref_channels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afp_deal.afpchannels', verbose_name='channel')),
                ('ref_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afp_deal.afpslots', verbose_name='slot')),
            ],
        ),
    ]
