# Generated by Django 3.2 on 2022-03-03 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency_client', '0002_alter_agencydetail_agency_pin'),
        ('afp_deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afpdeal',
            name='afp_base_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='afpdeal',
            name='afp_deal_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='afpdeal',
            name='afp_eff_rate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='afpdeal',
            name='ref_channels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afp_deal.afpchannels'),
        ),
        migrations.AlterField(
            model_name='afpdeal',
            name='ref_program_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afp_deal.afpprogramname'),
        ),
        migrations.AlterField(
            model_name='afpdeal',
            name='ref_promos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afp_deal.afppromos'),
        ),
        migrations.AlterField(
            model_name='afpdeal',
            name='ref_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afp_deal.afpslots'),
        ),
        migrations.CreateModel(
            name='FinalAFPDeal',
            fields=[
                ('afpdeal_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('afp_ro_number', models.CharField(max_length=100)),
                ('afp_ro_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('afp_total_ref', models.IntegerField(blank=True, null=True)),
                ('afp_agency_contact_ref', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='agency_client.agencycontact')),
                ('afp_agency_name_ref', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='agency_client.agencydetail')),
                ('afp_brand_name_ref', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='brand2', to='agency_client.customername')),
                ('afp_client_contact_ref', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='agency_client.customercontact')),
                ('afp_client_name_ref', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='client2', to='agency_client.customername')),
            ],
        ),
    ]
