# Generated by Django 3.2 on 2022-03-04 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('afp_deal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afpdeal',
            name='afp_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
