# Generated by Django 3.2.6 on 2022-03-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afp_deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afpdeal',
            name='ref_program_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afp_deal.afpprogramname', verbose_name='program Name'),
        ),
    ]
