# Generated by Django 3.2.11 on 2022-03-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afp_deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalafpdeal',
            name='afp_total_ref',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
