# Generated by Django 3.2.6 on 2022-03-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afp_deal', '0002_alter_afpdeal_ref_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='afpdeal',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
