# Generated by Django 3.2 on 2022-03-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afp_deal', '0003_remove_afpdeal_afp_deal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='afpdeal',
            name='afp_deal_id',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
