# Generated by Django 3.2.11 on 2022-01-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(default='default', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('item_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('subitem_id', models.CharField(default='default', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('subitem_name', models.CharField(max_length=200)),
                ('uom_desc', models.CharField(max_length=100)),
                ('uom_quantity', models.IntegerField()),
                ('uom_quantity_rate', models.IntegerField()),
            ],
        ),
    ]
