# Generated by Django 3.2.11 on 2022-01-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subitem',
            name='item',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
    ]
