# Generated by Django 3.2.6 on 2022-02-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fct_deal',
            name='deal_id',
        ),
    ]
