# Generated by Django 3.2.11 on 2022-03-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealfct',
            name='base_rate1',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='dealfct',
            name='base_rate2',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='dealfct',
            name='base_rate3',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
