# Generated by Django 4.0 on 2022-02-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fct_deal',
            name='total_rev',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
