# Generated by Django 3.2.11 on 2022-03-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0002_dealfct_finalfct'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalfct',
            name='fct_total_rev',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
