# Generated by Django 3.2 on 2022-02-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0003_auto_20220204_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_rate_table',
            name='ref_b_list',
        ),
        migrations.RemoveField(
            model_name='base_rate_table',
            name='ref_c_list',
        ),
    ]
