# Generated by Django 3.2 on 2022-02-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0005_fct_deal_chan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fct_deal',
            name='total_fct',
        ),
    ]
