# Generated by Django 3.2 on 2022-02-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0007_auto_20220205_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fct_deal',
            name='curr_fct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='eff_rate1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='eff_rate2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='eff_rate3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='fct1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='fct2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='fct3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='prev_yr_fct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='rev1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='rev2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='rev3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='total_rev',
            field=models.IntegerField(),
        ),
    ]
