<<<<<<< HEAD
# Generated by Django 3.2.11 on 2022-02-09 05:06
=======
# Generated by Django 3.2 on 2022-02-09 04:33
>>>>>>> 3e39837b78569563578493b52a8498a9899b44d0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0008_auto_20220208_1508'),
        ('deal_fct_nonfct', '0008_auto_20220208_1652'),
    ]

    operations = [
    ]
