# Generated by Django 3.2 on 2022-02-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0008_auto_20220208_1508'),
        ('deal_fct_nonfct', '0008_auto_20220208_1652'),
    ]

    operations = [
    ]
