# Generated by Django 3.2 on 2022-02-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0009_merge_0008_auto_20220208_1508_0008_auto_20220208_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='fct_deal',
            name='base_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='eff_rate3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='fct3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fct_deal',
            name='rev3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
