# Generated by Django 3.2 on 2022-02-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_fct_nonfct', '0010_auto_20220209_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fct_deal',
            old_name='base_rate',
            new_name='base_rate1',
        ),
        migrations.AddField(
            model_name='fct_deal',
            name='base_rate2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fct_deal',
            name='base_rate3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
