# Generated by Django 3.2.11 on 2022-01-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customertype_ctype_id'),
        ('item', '0002_subitem_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('p_id', models.CharField(default='default', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('plan_desc', models.CharField(max_length=200)),
                ('customertype', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='customer.customertype')),
                ('item', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('subitem', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='item.subitem')),
            ],
        ),
    ]
