# Generated by Django 3.2.11 on 2022-01-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='p_id',
            field=models.CharField(default='default', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
