# Generated by Django 3.2 on 2022-02-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencydetail',
            name='agency_pin',
            field=models.IntegerField(max_length=10),
        ),
    ]
