# Generated by Django 3.2.6 on 2022-03-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_deal_nfct',
            name='er',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='event_deal_nfct',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventfctmodel',
            name='eff_rate1',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventfctmodel',
            name='eff_rate2',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventfctmodel',
            name='eff_rate3',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventfctmodel',
            name='rev1',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventfctmodel',
            name='rev2',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventfctmodel',
            name='rev3',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventfctmodel',
            name='total_rev',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='fct_total_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='grandtotal_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='merit_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='nfct_total_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='ro_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='nfctgrandtotal',
            name='nfct_grandtotal',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12, primary_key=True, serialize=False),
        ),
    ]
