# Generated by Django 3.2.6 on 2022-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfctmodel',
            name='base_rate1',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='eventfctmodel',
            name='base_rate2',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='eventfctmodel',
            name='base_rate3',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
