# Generated by Django 3.2.6 on 2022-03-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_events', '0002_auto_20220307_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='ro_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='ro_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
