# Generated by Django 3.2.11 on 2022-02-02 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFP_Channels',
            fields=[
                ('channels', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AFP_ProgramName',
            fields=[
                ('program_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AFP_Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promos', models.CharField(blank=True, choices=[('10', '10'), ('20', '20'), ('30', '30')], max_length=20, null=True)),
                ('slot', models.CharField(blank=True, choices=[('10', '10'), ('22', '22')], max_length=20, null=True)),
                ('eff_rate', models.CharField(max_length=200)),
                ('ref_channels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_afp.afp_channels')),
                ('ref_program_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_afp.afp_programname')),
            ],
        ),
    ]
