# Generated by Django 3.2.11 on 2022-02-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_afp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events_Category',
            fields=[
                ('category_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
