# Generated by Django 3.2.11 on 2022-02-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_afp', '0002_events_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events_Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=200)),
                ('merit_money', models.CharField(max_length=200)),
                ('ref_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_afp.events_category')),
                ('ref_channels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_afp.afp_channels')),
            ],
        ),
    ]
