# Generated by Django 3.2.11 on 2022-01-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.CharField(max_length=20)),
                ('ba', models.CharField(max_length=20)),
                ('br', models.CharField(max_length=20)),
                ('er', models.CharField(max_length=20)),
                ('od', models.CharField(max_length=20)),
            ],
        ),
    ]
